# Generated by Django 5.2.9 on 2025-12-14 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteVisit',
        ),
    ]
